version: '3.9'

networks:
  dev_network:

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TPD37486IQ
      POSTGRES_DB: testdb